print("Afişaţi tabla înmulţirii cu numărul n.")
n = int(input("Dati un numar:"))
print("1*",n,"=",n*1,sep="")
print("2*",n,"=",n*2,sep="")
print("3*",n,"=",n*3,sep="")
print("4*",n,"=",n*4,sep="")
print("5*",n,"=",n*5,sep="")
print("6*",n,"=",n*6,sep="")
print("7*",n,"=",n*7,sep="")
print("8*",n,"=",n*8,sep="")
print("9*",n,"=",n*9,sep="")
print("10*",n,"=",n*10,sep="")