print("Date trei numere, să se calculeze toate sumele posibile de câte două numere. Afişarea să cuprindă şi termenii sumei, nu numai valoarea ei.")
a = int(input("Dati un numar: "))
b = int(input("Dati un numar: "))
c = int(input("Dati un numar: "))
print(a,"+",b,"=",a+b,sep="")
print(b,"+",c,"=",b+c,sep="")
print(a,"+",c,"=",a+c,sep="")